### ISSUE TITLE
Количество городов

### ISSUE THREAD

**Issue by artemovkr** [epogrebnyak/w2w#7]
В вики 1117 городов на 2010 год, в нашем списке 1105 на 2020.
В источнике (https://rosstat.gov.ru/compendium/document/13282) информации об общем количестве нет

**Comment by epogrebnyak** [comment]
@artemovkr  - нужны еще две ссылки - на вики и муницпалитеты из переписки в ТГ

**Comment by epogrebnyak** [comment]
https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%BE%D0%B2_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8

**Comment by epogrebnyak** [comment]
Отличия со списком 2010 года - Белоозерский.

```
[w for w in ws if w not in cs]
['Белоозерский', 'Горно-Алтайск', 'Дмитриев', 'Сергиев Посад']

[c for c in cs if c not in ws]
['Дмитриев-Льговский', 'Сергиев-Посад', 'тыс. человек']
```

**Comment by epogrebnyak** [comment]
Согласно https://mosreg.ru/download/document/981094 Белоозерский - город, в федеральный справочник видимо не успели внести.

В add_after() нужен `('Белоозерский', 17 898, 'Московская область')` 

Численность населения по https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D0%BB%D0%BE%D0%BE%D0%B7%D1%91%D1%80%D1%81%D0%BA%D0%B8%D0%B9#cite_note-2020MO-1
